version: '3.8'

networks:
  dev-network:
    driver: bridge

services:
  database:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=flowerdb
    ports:
      - "5433:5432"
    networks:
      - dev-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    networks:
      - dev-network
    environment:
      - PGADMIN_DEFAULT_EMAIL=dev@mail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  web:
    image: dotnettemplate
    container_name: webapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5135:80"
      - "7150:443"
    depends_on:
      database:
        condition: service_healthy
    links:
      - database
    networks:
      - dev-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_Kestrel__Certificates__Default__Password=devpass
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/Web.pfx
      - ConnectionStrings__Dev=Host=postgres_db;Port=5432;Database=flowerdb;Username=postgres;Password=admin
    volumes:
      - ~/.aspnet/https:/https:ro

volumes:
  local_pgdata:
  pgadmin-data: